version: '3'
services:
  web:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tp_music
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123456